### ISSUE TITLE
Always use node buildin npm to install packages

### ISSUE THREAD

**Issue by viceice** [containerbase/base#1136]
Otherwise we can call a newer npm on an old node.

- https://github.com/renovatebot/renovate/discussions/22495#discussioncomment-6339653

**Comment by rarkins** [comment]
What I'd like is this (if it's not too complex): every time `install-tool node` is run, the `npm` in the path should be the one which comes included with `node`.

**Comment by viceice** [comment]
> What I'd like is this (if it's not too complex): every time `install-tool node` is run, the `npm` in the path should be the one which comes included with `node`.

this should already happen. after any npm tool or node version change it should update the shell wrapper.

**Comment by rarkins** [comment]
Yeah, seems like it's yarn which got stuck/broke and not npm
