### ISSUE TITLE
Golang no longer trim the 0 patch version for new releases

### ISSUE THREAD

**Issue by maxbrunet** [containerbase/base#1287]
For 1.21+, this does not seem to apply anymore:

https://github.com/containerbase/base/blob/ce376824eeac2db23a17e27b91928bd1e92af55f/src/usr/local/containerbase/tools/v2/golang.sh#L37-L39

* https://dl.google.com/go/go1.21.linux-amd64.tar.gz (404)
* https://dl.google.com/go/go1.21.0.linux-amd64.tar.gz (working)

> Go 1.21 introduces a small change to the numbering of releases. In the past, we used Go 1._N_ to refer to both the overall Go language version and release family as well as the first release in that family. Starting in Go 1.21, the first release is now Go 1._N_.0. Today we are releasing both the Go 1.21 language and its initial implementation, the Go 1.21.0 release. These notes refer to "Go 1.21"; tools like go version will report "`go1.21.0`" (until you upgrade to Go 1.21.1). See “[Go versions](https://go.dev/doc/toolchain#versions)” in the "Go Toolchains" documentation for details about the new version numbering.

https://go.dev/doc/go1.21#introduction

Older versions are unchanged, e.g.: https://dl.google.com/go/go1.20.linux-amd64.tar.gz (see also: https://github.com/golang/dl)

**Comment by viceice** [comment]
will fix it today
