### ISSUE TITLE
semver regex is broken for Java 21

### ISSUE THREAD

**Issue by bduisenov** [containerbase/base#1677]
In a util.sh#check_semver there's a regex used to verify the semver pattern. With the latest adoptium java 21 version, semvers are defined as `21.0.1+12.1.LTS` instead of prev. `17.0.9+9` and because of this it is not possible to use `install-tool java 21.0.1+12.1.LTS`

**Comment by viceice** [comment]
I've fixed the semver, but there is no linux binaries returned by `https://api.adoptium.net/v3/assets/version/21.0.1%2B12.1.LTS?heap_size=normal&image_type=jdk&page=0&page_size=10&project=jdk&semver=true`

So that version isn't usable at all 😕

**Comment by bduisenov** [comment]
I could find this version `21.0.1+12.0.LTS` for linux
