### ISSUE TITLE
Using install-tool dotnet v2.2 does not work with Ubuntu 22.04

### ISSUE THREAD

**Issue by kyallanum-MND** [containerbase/base#2042]
When using ``ARG BASE_IMAGE=amd64/ubuntu:22.04`` an error is thrown when attempting to run ``install-tool dotnet`` version 2.2.207.

This is due to a usable version of libssl not being installed for dotnet properly. There is a way to fix this on this Unity forum thread: https://forum.unity.com/threads/workaround-for-libssl-issue-on-ubuntu-22-04.1271405/

I was able to fix this by adding the following lines to my Dockerfile before installing dotnet:

```Dockerfile
RUN curl -fsSL "http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5.13_amd64.deb" --output "libssl1.0.0_1.0.2n-1ubuntu5.13_amd64.deb" && \
        dpkg -i libssl1.0.0_1.0.2n-1ubuntu5.13_amd64.deb && \
        rm libssl1.0.0_1.0.2n-1ubuntu5.13_amd64.deb

RUN curl -fsSL "http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0-dev_1.0.2n-1ubuntu5.13_amd64.deb" --output "libssl1.0-dev_1.0.2n-1ubuntu5.13_amd64.deb" && \
        dpkg -i libssl1.0-dev_1.0.2n-1ubuntu5.13_amd64.deb && \
        rm libssl1.0-dev_1.0.2n-1ubuntu5.13_amd64.deb
```

**Comment by rarkins** [comment]
Needs a minimal Dockerfile for reproduction

**Comment by viceice** [comment]
I don't like to support this. dotnet v2.2 is very long time eol and is full of bugs and security issues.

even dotnet v3 and v5 are already eol.

why do you need dotnet v2.2 on our containerbase image?

don't use our images for product workloads. we do some special things for renovate which makes the images a little weaker.

**Comment by viceice** [comment]
https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

btw: more than 5 years eol

**Comment by kyallanum-MND** [comment]
@viceice Mend uses containerbase to install dependencies on the scanner docker container for our Repository Integrations. Renovate uses it, but so does the actual scanning solution.

At the end of the day the container needs to install multiple different versions of different package managers, (dotnet 2, 3, and more) to ensure that customers can perform SCA scans on even old projects.

I can provide a minimal Dockerfile for the reproduction. At the end of the day installing these versions is fine on Ubuntu 20.04, but when it comes to Ubuntu 22.04, it needs libssl installed as well (as shown above). @rarkins asked me directly to open up this. Can we please reconsider this issue?

**Comment by viceice** [comment]
can't you just simply install that package manually? 🤔

I'm pretty sure you don't need such an old dotnet version to scan old projects. dotnet sdk is very compatible in a backward manner. so please try to scan a v2.2 project with a newer SDK.

Duplicate of #2041

**Comment by viceice** [comment]
Duplicate of #2041
