### ISSUE TITLE
`nix`: validate checksums

### ISSUE THREAD

**Issue by viceice** [containerbase/base#2066]
- use releases instead of hydra, should work for v2+
- use `0` for patch from v2.5+
- sha256
- https://releases.nixos.org/?prefix=nix/

**Comment by viceice** [comment]
I'm thinking about building our own static nix build. do you know an easy way to build this with an docker image?

**Comment by sandydoo** [comment]
I suppose the easiest way would be to use the [nixos/nix container](https://github.com/nixos/nix/pkgs/container/nix), checkout the nix repo by tag, and run `nix build .#nix-static`.

**Comment by viceice** [comment]
- https://github.com/containerbase/nix-prebuild

**Comment by viceice** [comment]
@sandydoo after #3087 is merged it should be easier to port to typescript 🤗
