### ISSUE TITLE
Support readonly root filesystem

### ISSUE THREAD

**Issue by viceice** [containerbase/base#2078]
### general

- `/usr/local/bin` is symlinked to `/opt/containerbase/bin`
- `/usr/local/lib` is symlinked to `/opt/containerbase/lib`
- tool prepare state is stored at `/var/lib/containerbase`
- all cache files are stored at `/tmp/containerbase`
- files and folders in user home are symlinked to `/tmp/containerbase/cache` (eg `.cache`, `.npmrc`, `.npm`)

### `binarySource=global`
- needs `/tmp` writable

### `binarySource=install`
- needs `/tmp` writable
- needs `/opt/containerbase` writable
---
*related issues*
- #101
- #380
- #1384
- #1385

**Comment by rarkins** [comment]
It cannot be stopped??

**Comment by rarkins** [comment]
I'm not sure I fully follow, but I guess you mean that when the user mounts a volume to /opt/containerbase then anything we've put there prior is lost. So you're planning to put it in another location and symlink it over whenever the container runs?

**Comment by viceice** [comment]
Yes, that's the core idea.

When later running `install-tool` as user it will simply install to `/opt/containerbase` as now.
I can propably also check and run the `containerbase-cli restore` command implicit from `install-tool`  when something is missing inside `/opt/containerbase`.

**Comment by rarkins** [comment]
Would it be a viable alternative to allow the user to configure the containerbase rw location via env variable? If configured then the restore happens from /opt/containerbase otherwise /opt/containerbase is used? Or is it too hard to set up PATH etc?

**Comment by viceice** [comment]
we can't ensure path then. a user would need to explicit set it 😞
