### ISSUE TITLE
Move poetry installation script source url to new location

### ISSUE THREAD

**Issue by Chumper** [containerbase/base#339]
![image (11)](https://user-images.githubusercontent.com/919670/158567516-efee9b2f-6057-45c2-a81a-f8e835d26c66.png)

**Comment by viceice** [comment]
Reverted in #343 because of flaxy download url 😕

**Comment by Chumper** [comment]
Do you have a link where the flakiness is visible?
Seems like the CDN of github is better than the one from the poetry project

**Comment by viceice** [comment]
sure: https://github.com/containerbase/buildpack/runs/5580677691?check_suite_focus=true#step:9:2717

failed on two attempts, so reverted for now 🤷‍♂️

**Comment by Chumper** [comment]
Fine with me, should we open a ticket on the poetry project asking for investigation or are we OK with the old install path until it kicks the bucket?

**Comment by viceice** [comment]
Closing, as we are now using a virtualenv to install poetry. It's nearly same what the poetry installer does
