### ISSUE TITLE
Node v18+ no longer works on Ubuntu 18.04

### ISSUE THREAD

**Issue by viceice** [containerbase/base#362]
Node v18+ needs a more modern glibc, so the precompiled binaries are no longer working on Ubuntu 18.04.

Idea: Exit with error when trying to install Node v18+ on buildpack on 18.04.

- https://nodejs.org/en/blog/release/v18.0.0/

**Comment by rarkins** [comment]
Can this be closed?

**Comment by viceice** [comment]
sure, we dropped 18.04 support
