### ISSUE TITLE
Error in sbt installation verification process after installation

### ISSUE THREAD

**Issue by Arye-H-WS** [containerbase/base#503]
Hi!

During the installation of sbt, the following error message returns:

> RUN install-tool sbt
> sha256:9749d074c919117e177b9116c24cf381141fa938169a69c5191595dbf2f5d954
> installing v2 tool sbt v1.7.1
> linking tool sbt v1.7.1
> copying runtime jar...
> [info] [launcher] getting org.scala-sbt sbt 1.7.1  (this may take some time)...
> [info] [launcher] getting Scala 2.12.16 (for sbt)...
> java.lang.IllegalStateException: **cannot run sbt from root directory without -Dsbt.rootdir=true; see sbt/sbt#1458**
> 	at sbt.BuiltinCommands$.$anonfun$checkRoot$1(Main.scala:1149)
> 	at sbt.BuiltinCommands$.$anonfun$checkRoot$1$adapted(Main.scala:1146)
> 	at scala.Option.foreach(Option.scala:407)
> 	at sbt.BuiltinCommands$.checkRoot(Main.scala:1146)
> 	at sbt.BuiltinCommands$.$anonfun$writeSbtVersion$1(Main.scala:1159)
> 	at sbt.Command$.$anonfun$command$2(Command.scala:97)
> 	at sbt.Command$.process(Command.scala:189)
> 	at sbt.MainLoop$.$anonfun$processCommand$5(MainLoop.scala:245)
> 	at scala.Option.getOrElse(Option.scala:189)
> 	at sbt.MainLoop$.process$1(MainLoop.scala:245)
> 	at sbt.MainLoop$.processCommand(MainLoop.scala:278)
> 	at sbt.MainLoop$.$anonfun$next$5(MainLoop.scala:163)
> 	at sbt.State$StateOpsImpl$.runCmd$1(State.scala:289)
> 	at sbt.State$StateOpsImpl$.process$extension(State.scala:325)
> 	at sbt.MainLoop$.$anonfun$next$4(MainLoop.scala:163)
> 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
> 	at sbt.MainLoop$.next(MainLoop.scala:163)
> 	at sbt.MainLoop$.run(MainLoop.scala:144)
> 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:119)
> 	at sbt.io.Using.apply(Using.scala:27)
> 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:112)
> 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:66)
> 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:51)
> 	at sbt.MainLoop$.runLogged(MainLoop.scala:42)
> 	at sbt.StandardMain$.runManaged(Main.scala:215)
> 	at sbt.xMain$.$anonfun$run$11(Main.scala:133)
> 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
> 	at scala.Console$.withIn(Console.scala:230)
> 	at sbt.internal.util.Terminal$.withIn(Terminal.scala:577)
> 	at sbt.internal.util.Terminal$.$anonfun$withStreams$1(Terminal.scala:358)
> 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
> 	at scala.Console$.withOut(Console.scala:167)
> 	at sbt.internal.util.Terminal$.$anonfun$withOut$2(Terminal.scala:567)
> 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
> 	at scala.Console$.withErr(Console.scala:196)
> 	at sbt.internal.util.Terminal$.withOut(Terminal.scala:567)
> 	at sbt.internal.util.Terminal$.withStreams(Terminal.scala:358)
> 	at sbt.xMain$.withStreams$1(Main.scala:87)
> 	at sbt.xMain$.run(Main.scala:121)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:57)
> 	at sbt.xMain.run(Main.scala:46)
> 	at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
> 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
> 	at xsbt.boot.Launch$.run(Launch.scala:149)
> 	at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
> 	at xsbt.boot.Launch$.launch(Launch.scala:159)
> 	at xsbt.boot.Launch$.apply(Launch.scala:44)
> 	at xsbt.boot.Launch$.apply(Launch.scala:21)
> 	at xsbt.boot.Boot$.runImpl(Boot.scala:78)
> 	at xsbt.boot.Boot$.run(Boot.scala:73)
> 	at xsbt.boot.Boot$.main(Boot.scala:21)
> 	at xsbt.boot.Boot.main(Boot.scala)
> [error] Use 'last' for the full log.
> sbt script version: 1.7.1
> DONE 29.6s

I should note that, in fact, sbt is installed properly, the problem probably occurs only in the installation verification process that is performed automatically after installation.

Many thanks!

---
```Dockerfile
# This default may be swapped for any compatible base image
ARG BASE_IMAGE=amd64/ubuntu:18.04

# This buildpack is used for tool installation and user/directory setup
FROM containerbase/buildpack:4.13.2 AS buildpack

FROM ${BASE_IMAGE} as base

# The buildpack supports custom user
ARG USER_NAME=test-user
ARG USER_ID=1000
ARG USER_HOME=/home/${USER_NAME}
ARG APT_HTTP_PROXY

# Set env and shell
ENV BASH_ENV=/usr/local/etc/env
SHELL ["/bin/bash" , "-c"]

# Set up buildpack
COPY --from=buildpack /usr/local/bin/ /usr/local/bin/
COPY --from=buildpack /usr/local/buildpack/ /usr/local/buildpack/
RUN install-buildpack

# renovate: datasource=github-tags depName=git lookupName=git/git
ARG GIT_VERSION=2.34.1
RUN install-tool git

# renovate: datasource=docker depName=openjdk versioning=docker
ARG JAVA_VERSION=11.0.13+8
RUN install-tool java

# renovate: datasource=gradle-version depName=gradle versioning=gradle
ARG GRADLE_VERSION=6.9.1
RUN install-tool gradle

# renovate: datasource=maven depName=maven lookupName=org.apache.maven:maven
ARG MAVEN_VERSION=3.6.3
RUN install-tool maven

# renovate: datasource=github-releases depName=scala lookupName=scala/scala
ARG SCALA_VERSION=2.13.8
RUN install-tool scala

# renovate: datasource=github-releases depName=sbt lookupName=sbt/sbt
ARG SBT_VERSION=1.7.1
RUN install-tool sbt

ENV DEBIAN_FRONTEND noninteractive
ENV LANGUAGE	en_US.UTF-8
ENV LANG    	en_US.UTF-8
ENV LC_ALL  	en_US.UTF-8


RUN chgrp -R 0 ${USER_HOME} && chmod -R g=u ${USER_HOME}

### Switch User ###
ENV HOME ${USER_HOME}
WORKDIR ${USER_HOME}
USER ${USER_ID}
```

@Arye-H-WS Please post as code section next time

**Comment by rarkins** [comment]
Please provide the `Dockerfile` which reproduces this

**Comment by Arye-H-WS** [comment]
[sbt-Dockerfile.zip](https://github.com/containerbase/buildpack/files/9459335/sbt-Dockerfile.zip)

Thanks!

**Comment by viceice** [comment]
```Dockerfile
# This default may be swapped for any compatible base image
ARG BASE_IMAGE=amd64/ubuntu:18.04

# This buildpack is used for tool installation and user/directory setup
FROM containerbase/buildpack:4.13.2 AS buildpack

FROM ${BASE_IMAGE} as base

# The buildpack supports custom user
ARG USER_NAME=test-user
ARG USER_ID=1000
ARG USER_HOME=/home/${USER_NAME}
ARG APT_HTTP_PROXY

# Set env and shell
ENV BASH_ENV=/usr/local/etc/env
SHELL ["/bin/bash" , "-c"]

# Set up buildpack
COPY --from=buildpack /usr/local/bin/ /usr/local/bin/
COPY --from=buildpack /usr/local/buildpack/ /usr/local/buildpack/
RUN install-buildpack

# renovate: datasource=github-tags depName=git lookupName=git/git
ARG GIT_VERSION=2.34.1
RUN install-tool git

# renovate: datasource=docker depName=openjdk versioning=docker
ARG JAVA_VERSION=11.0.13+8
RUN install-tool java

# renovate: datasource=gradle-version depName=gradle versioning=gradle
ARG GRADLE_VERSION=6.9.1
RUN install-tool gradle

# renovate: datasource=maven depName=maven lookupName=org.apache.maven:maven
ARG MAVEN_VERSION=3.6.3
RUN install-tool maven

# renovate: datasource=github-releases depName=scala lookupName=scala/scala
ARG SCALA_VERSION=2.13.8
RUN install-tool scala

# renovate: datasource=github-releases depName=sbt lookupName=sbt/sbt
ARG SBT_VERSION=1.7.1
RUN install-tool sbt

ENV DEBIAN_FRONTEND noninteractive
ENV LANGUAGE	en_US.UTF-8
ENV LANG    	en_US.UTF-8
ENV LC_ALL  	en_US.UTF-8


RUN chgrp -R 0 ${USER_HOME} && chmod -R g=u ${USER_HOME}

### Switch User ###
ENV HOME ${USER_HOME}
WORKDIR ${USER_HOME}
USER ${USER_ID}
```

@Arye-H-WS Please post as code section next time

**Comment by rarkins** [comment]
You are installing everything as root - is that intentional?

**Comment by viceice** [comment]
`RUN chgrp -R 0 ${USER_HOME} && chmod -R g=u ${USER_HOME}` shouldn't ne required

**Comment by viceice** [comment]
the output comes from here
https://github.com/containerbase/buildpack/blob/0fe4028744e92366751cc9763a469b3fd9c51fd3/src/usr/local/buildpack/tools/v2/sbt.sh#L27

**Comment by viceice** [comment]
we're installing sdbt as root here without any issues:
https://github.com/containerbase/buildpack/blob/0fe4028744e92366751cc9763a469b3fd9c51fd3/test/java/Dockerfile#L138

**Comment by viceice** [comment]
Please use `adoptium-java` datasource
```Dockerfile
# renovate: datasource=adoptium-java packageName=java-jre
RUN install-tool java 11.0.16+8

# or 
# renovate: datasource=adoptium-java packageName=java
RUN install-tool java 11.0.16+8
```

**Comment by Arye-H-WS** [comment]
Hi!
Thank you very much for the responses!

I updated the docker according to the versions you are using in the test, but unfortunately the problem still exists.
And regarding the question of whether we intentionally use root privileges, I assume so, but if it is important I will check with my company (and yours - @rarkins :) )

Many thanks!

```
# This default may be swapped for any compatible base image
ARG BASE_IMAGE=amd64/ubuntu:18.04

# This buildpack is used for tool installation and user/directory setup
FROM containerbase/buildpack:4.13.2 AS buildpack

FROM ${BASE_IMAGE} as base

# The buildpack supports custom user
ARG USER_NAME=test-user
ARG USER_ID=1000
ARG USER_HOME=/home/${USER_NAME}
ARG APT_HTTP_PROXY

# Set env and shell
ENV BASH_ENV=/usr/local/etc/env
SHELL ["/bin/bash" , "-c"]

# Set up buildpack
COPY --from=buildpack /usr/local/bin/ /usr/local/bin/
COPY --from=buildpack /usr/local/buildpack/ /usr/local/buildpack/
RUN install-buildpack

# renovate: datasource=github-tags depName=git lookupName=git/git
ARG GIT_VERSION=2.34.1
RUN install-tool git

# renovate: datasource=adoptium-java depName=java
ARG JAVA_JDK_VERSION=17.0.4+8
RUN install-tool java-jdk

# renovate: datasource=gradle-version depName=gradle versioning=gradle
ARG GRADLE_VERSION=7.3
RUN install-tool gradle

# renovate: datasource=github-releases depName=scala lookupName=scala/scala
ARG SCALA_VERSION=2.13.8
RUN install-tool scala

# renovate: datasource=github-releases packageName=sbt/sbt
ARG SBT_VERSION=v1.7.1
RUN install-tool sbt

ENV DEBIAN_FRONTEND noninteractive
ENV LANGUAGE	en_US.UTF-8
ENV LANG    	en_US.UTF-8
ENV LC_ALL  	en_US.UTF-8

RUN chgrp -R 0 ${USER_HOME} && chmod -R g=u ${USER_HOME}

### Switch User ###
ENV HOME ${USER_HOME}
WORKDIR ${USER_HOME}
USER ${USER_ID}
```

**Comment by viceice** [comment]
can now reproduce.

our tests to `WORKDIR /test` so that's why we don't get the failure. Will add a workaround now.
