### ISSUE TITLE
[yarn] Install fails for yarn versions > 1.x

### ISSUE THREAD

**Issue by patrickpichler** [containerbase/base#558]
Apparently yarn can no longer be installed via the `yarn` npm package (only version 1.x). The 
install script for yarn and yarn slim fails if one tries to install it for e.g. version `3.2.2`. 

https://yarnpkg.com/getting-started/install

We noticed that issue when using renovate with `binarysource = install`, hence I'm not sure
if the issue fits here.

**Comment by viceice** [comment]
yarn V2+ can't installed via npm. you need to install yarn v1 or use corepack.

i suggest to use corepack and yarn V3+.

please open a discussion in main renovate repo for more questions.
