### ISSUE TITLE
Proposal: user -> ubuntu

### ISSUE THREAD

**Issue by rarkins** [containerbase/base#572]
Reasons to do this:
- Containerbase only works using Ubuntu images today
- Changing the base image in future would be a large task, definitely a breaking change anyway
- Renovate and Mend images have been using `ubuntu` as the user for so long that changing them to use `user` instead would be much more work

So therefore my proposal is to refactor Containerbase to default to `ubuntu` instead of `user` here: https://github.com/containerbase/base/blob/5354700b5b7dc262783ea45a642dd82e17241a51/src/usr/local/bin/install-buildpack#L8

This would allow us to deprecate the `renovate/*` containerbase (buildpack) images faster.

Any reasons why not to do this?

**Comment by viceice** [comment]
I think the sidecar image is already running as user and the username seems to not matter as long as the user id matches.

**Comment by viceice** [comment]
btw: it was your idea to switch to a more general username. 😅
