### ISSUE TITLE
Elixir install issue?

### ISSUE THREAD

**Issue by rarkins** [containerbase/base#603]
This was raised to my attention: https://elixirforum.com/t/elixir-1-14-github-release-format-change-causing-some-issues/50095

There's a comment in there about scoop switching to `repo.hex.pm`. Perhaps this? https://elixir-lang.org/install.html#mirrors-and-nightly-builds

**Comment by rarkins** [comment]
https://github.com/containerbase/base/blob/main/src/usr/local/buildpack/tools/v2/elixir.sh#L7

**Comment by rarkins** [comment]
Fixed already by https://github.com/containerbase/base/commit/d7008236797e3afc58a692c21b884a7ddbc8af22 ?

**Comment by viceice** [comment]
yes, already fixed 🎉
