### ISSUE TITLE
Publish to GHCR

### ISSUE THREAD

**Issue by rarkins** [containerbase/base#796]
Let's publish containerbase images to ghcr too, and then add a replacement rule to start using them instead of Docker Hub.

I plan to keep our images on Docker Hub for at least one year (they are referenced from within some Dockerfiles which Mend customers use) but it would be good to start the switch as soon as possible.

**Comment by viceice** [comment]
already done a long time ago 😃

**Comment by rarkins** [comment]
Oh whoops, so should we recommend using/replacing Docker Hub references with ghcr from now on?

**Comment by viceice** [comment]
🤷‍♂️ your decision
