### ISSUE TITLE
Extended Java version support

### ISSUE THREAD

**Issue by rarkins** [containerbase/base#885]
Is it possible to support installing Java 7, maybe if it's a new/special `install-tool`? https://www.oracle.com/java/technologies/javase/javase7-archive-downloads.html

Do we also support today all the versions listed here? https://adoptium.net/temurin/archive/ e.g. including Java 16, 18, 19, 20?

**Comment by viceice** [comment]
why java 7? isn't v8 fully compatible?

we support all versions which the adoptium API returns.

**Comment by rarkins** [comment]
There are projects which have 1.7 in a pom.xml and we need to run mvn commands against them.

**Comment by viceice** [comment]
Oracle needs login to download older jdk's. So i don't think it's easily possible to get a jdk lower than v8.

https://github.com/jenkinsci/jdk-tool-plugin/blob/master/src/main/java/hudson/tools/JDKInstaller.java

**Comment by viceice** [comment]
The only option i see it so self-compile from old ubuntu sources[^1]. but i'm not sure if it's possible on modern ubuntu.

Should i try to compile?

[^1]: https://git.launchpad.net/ubuntu/+source/openjdk-7/tree/README?h=applied/ubuntu/trusty-updates

**Comment by viceice** [comment]
We could also try azul zulu[^1]

[^1]: https://www.azul.com/downloads/?version=java-6-lts&package=jdk#zulu

**Comment by viceice** [comment]
we probably need to hardcode some known good old java versions for zulu because of their complex versioning

**Comment by viceice** [comment]
Just to remember another good datasource for zulu and others from `asdf-java`[^1] 

[^1]: https://github.com/halcyon/asdf-java/blob/4a916d3bd2699c6503153099d49b8df6c7fc9e87/data/jdk-linux-x86_64.tsv#L1781
