### ISSUE TITLE
Add Conan support

### ISSUE THREAD

**Issue by rarkins** [containerbase/base#948]

**Comment by TobiaszSML** [comment]
Hello @viceice.

I'm working on #21912 and #948 is a subtask of #21912. On one hand I can see that this task is in progress, on the other hand the last commit was pushed 10 months ago. Can you tell me what the status of #948 is? Do you want to finish #948? Or maybe #948 is not necessary and can be extracted from #21912 into a separate task?

BR,
Tobiasz.

**Comment by viceice** [comment]
I started in #1071 but never got it finished. feel free to take it to the next level. see other python tools like `pdm`
