### ISSUE TITLE
Use fully-qualified container image references

### ISSUE THREAD

**Issue by JamieMagee** [containerbase/base#957]
We use a lot of short container references like `ubuntu:20.04` or `containerbase/base`. But these can sometimes be confusing, especially as we are also pushing images to the GitHub container registry `ghcr.io`. And they are also not standardized across container runtimes. For example, running `podman pull ubuntu:20.04` will result in the error `Error: short-name "ubuntu:20.04" did not resolve to an alias`.

Instead we should use fully-qualified references, like `docker.io/library/ubuntu:20.04` or `docker.io/containerbase/base`.

**Comment by viceice** [comment]
all done
